# -*- coding: utf-8 -*-
"""astar_planner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P4FOLoqRsq9ocrcUoo15ioA_zXJ5AXj0
"""

"""
AeroNet Lite - Module 3a: A* Path Planner
==========================================
Implements A* search on the 10x10 city grid.

Route per delivery: Hub -> Pickup -> Drop-off -> Hub
Each segment is solved independently using astar().

A* Design (as per project spec):
  - State       : grid coordinate (row, col)
  - Actions     : up, down, left, right
  - Path cost   : 1.0 per normal move, 0.8 for commercial corridor
  - Blocked     : cells where no_fly = True
  - Heuristic   : Manhattan distance (admissible for 4-direction grids)
"""

import heapq



# Helper functions


def manhattan(a, b):
    """Manhattan distance between two (row, col) coordinates."""
    return abs(a[0] - b[0]) + abs(a[1] - b[1])


def get_neighbors(row, col, grid):
    """
    Return valid adjacent cells (up, down, left, right).
    Skips cells that are out of grid bounds.
    """
    directions = [(-1, 0), (1, 0), (0, -1), (0, 1)]
    rows, cols = len(grid), len(grid[0])
    neighbors = []
    for dr, dc in directions:
        nr, nc = row + dr, col + dc
        if 0 <= nr < rows and 0 <= nc < cols:
            neighbors.append((nr, nc))
    return neighbors


def get_move_cost(row, col, grid):
    """
    Movement cost to enter a cell.
    Commercial corridors cost 0.8, all other cells cost 1.0.
    """
    cell = grid[row][col]
    if getattr(cell, 'is_commercial_corridor', False):
        return 0.8
    return 1.0


# ---------------------------------------------------------------------------
# Core A* algorithm
# ---------------------------------------------------------------------------

def astar(start, goal, grid):
    """
    Find the shortest safe path from start to goal on the grid using A*.

    Parameters
    ----------
    start : tuple (row, col)  - starting cell
    goal  : tuple (row, col)  - destination cell
    grid  : 2D list of Cell objects (from grid_model.py)

    Returns
    -------
    path       : list of (row, col) tuples from start to goal (inclusive)
                 Empty list if no path found.
    total_cost : float - total movement cost along the path
    message    : str   - 'success' or a description of why it failed
    """

    # --- Edge case checks ---
    if grid[start[0]][start[1]].no_fly:
        return [], 0.0, f"FAILED: Start cell {start} is a no-fly zone"

    if grid[goal[0]][goal[1]].no_fly:
        return [], 0.0, f"FAILED: Goal cell {goal} is a no-fly zone"

    if start == goal:
        return [start], 0.0, "success"

    # --- Priority queue: (f_cost, g_cost, node) ---
    open_set = []
    heapq.heappush(open_set, (manhattan(start, goal), 0.0, start))

    # Best known cost from start to each node
    g_cost = {start: 0.0}

    # Parent map to reconstruct path
    parent = {start: None}

    visited = set()

    while open_set:
        f, g, current = heapq.heappop(open_set)

        if current in visited:
            continue
        visited.add(current)

        # Goal reached — reconstruct and return path
        if current == goal:
            path = []
            node = goal
            while node is not None:
                path.append(node)
                node = parent[node]
            path.reverse()
            return path, round(g, 2), "success"

        # Expand neighbors
        for nr, nc in get_neighbors(current[0], current[1], grid):
            neighbor = (nr, nc)

            # Skip no-fly cells
            if grid[nr][nc].no_fly:
                continue

            new_g = g + get_move_cost(nr, nc, grid)

            if neighbor not in g_cost or new_g < g_cost[neighbor]:
                g_cost[neighbor] = new_g
                f_cost = new_g + manhattan(neighbor, goal)
                heapq.heappush(open_set, (f_cost, new_g, neighbor))
                parent[neighbor] = current

    # Open set exhausted — no path exists
    return [], 0.0, f"FAILED: No safe path from {start} to {goal}"


# ---------------------------------------------------------------------------
# Delivery route planner (Hub -> Pickup -> Drop-off -> Hub)
# ---------------------------------------------------------------------------

def plan_delivery_route(hub, pickup, dropoff, grid):
    """
    Plan a full delivery route in three A* segments:
        Segment 1: hub    -> pickup
        Segment 2: pickup -> dropoff
        Segment 3: dropoff -> hub

    Parameters
    ----------
    hub     : tuple (row, col) - drone's home hub
    pickup  : tuple (row, col) - package pickup location
    dropoff : tuple (row, col) - delivery destination
    grid    : 2D list of Cell objects

    Returns
    -------
    full_path  : list of (row, col) - complete route (segments joined, no duplicates at joins)
    total_cost : float
    segments   : dict with per-segment paths, costs, and messages
    success    : bool - True only if all three segments found a valid path
    """

    seg1_path, seg1_cost, seg1_msg = astar(hub, pickup, grid)
    seg2_path, seg2_cost, seg2_msg = astar(pickup, dropoff, grid)
    seg3_path, seg3_cost, seg3_msg = astar(dropoff, hub, grid)

    segments = {
        "hub_to_pickup":    {"path": seg1_path, "cost": seg1_cost, "message": seg1_msg},
        "pickup_to_dropoff":{"path": seg2_path, "cost": seg2_cost, "message": seg2_msg},
        "dropoff_to_hub":   {"path": seg3_path, "cost": seg3_cost, "message": seg3_msg},
    }

    all_ok = all(s["message"] == "success" for s in segments.values())

    if all_ok:
        # Join segments without repeating junction cells
        full_path = seg1_path + seg2_path[1:] + seg3_path[1:]
        total_cost = round(seg1_cost + seg2_cost + seg3_cost, 2)
    else:
        full_path = []
        total_cost = 0.0

    return full_path, total_cost, segments, all_ok


# ---------------------------------------------------------------------------
# Quick standalone test
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    # Import grid model (Member 1's file); fall back to a minimal inline grid for testing
    try:
        from grid_model import build_sample_grid
        grid = build_sample_grid()
        print("Loaded grid from grid_model.py")
    except ImportError:
        from dataclasses import dataclass

        @dataclass
        class Cell:
            row: int
            col: int
            zone: str = "Open"
            no_fly: bool = False
            is_commercial_corridor: bool = False

        grid = [[Cell(row=r, col=c) for c in range(10)] for r in range(10)]

        # Add a couple of commercial corridors
        for r, c in [(3, 4), (3, 5), (4, 5)]:
            grid[r][c].is_commercial_corridor = True

        # Add a no-fly obstacle to test routing around it
        grid[4][4].no_fly = True
        grid[5][4].no_fly = True

        print("grid_model.py not found — using minimal inline grid for testing")

    print("\n--- Test 1: Simple path (0,0) → (9,9) ---")
    path, cost, msg = astar((0, 0), (9, 9), grid)
    print(f"  Status : {msg}")
    print(f"  Cost   : {cost}")
    print(f"  Length : {len(path)} steps")
    print(f"  Path   : {path}")

    print("\n--- Test 2: Path blocked by no-fly cells ---")
    path2, cost2, msg2 = astar((4, 3), (4, 5), grid)
    print(f"  Status : {msg2}")
    print(f"  Path   : {path2}")

    print("\n--- Test 3: Full delivery route Hub(2,5) → Pickup(0,0) → Dropoff(9,9) → Hub(2,5) ---")
    full_path, total_cost, segments, ok = plan_delivery_route(
        hub=(2, 5), pickup=(0, 0), dropoff=(9, 9), grid=grid
    )
    print(f"  All segments found : {ok}")
    print(f"  Total cost         : {total_cost}")
    for seg_name, seg_data in segments.items():
        print(f"  {seg_name}: cost={seg_data['cost']}, status={seg_data['message']}, steps={len(seg_data['path'])}")