# -*- coding: utf-8 -*-
"""delivery_simulator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P4FOLoqRsq9ocrcUoo15ioA_zXJ5AXj0
"""

"""
AeroNet Lite - Module 3b: Delivery Simulator + Disruption Handler
=================================================================
Handles:
  - Drone state tracking (position, route, status)
  - Assigning deliveries to drones
  - Moving drones step by step along their planned routes
  - Real-time disruption: when a no-fly cell is activated mid-simulation,
    any drone whose remaining route passes through that cell is rerouted
    using A* from its current position

Event log format matches the project spec exactly:
  Step 6:  No-fly cell activated at (4, 7)
  Step 7:  Drone D2 rerouted successfully using A*
  Step 20: Simulation complete. 8 completed, 1 delayed, 1 failed.
"""

from dataclasses import dataclass, field
from typing import Optional
from astar_planner import astar, plan_delivery_route


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------

@dataclass
class Delivery:
    """A single delivery task."""
    delivery_id: str
    hub: tuple          # (row, col) of home hub
    pickup: tuple       # (row, col) of pickup point
    dropoff: tuple      # (row, col) of drop-off point
    weight: float = 1.0 # kg

    # Status: 'pending', 'assigned', 'in_progress', 'completed', 'delayed', 'failed'
    status: str = "pending"
    assigned_drone: Optional[str] = None


@dataclass
class Drone:
    """A single drone in the fleet."""
    drone_id: str
    drone_type: str         # 'light' or 'heavy'
    position: tuple         # current (row, col)
    home_hub: tuple         # hub it returns to

    # Route is a flat list of (row, col) waypoints yet to be visited
    route: list = field(default_factory=list)
    route_cost: float = 0.0

    # Status: 'idle', 'en_route', 'returning', 'grounded'
    status: str = "idle"

    current_delivery: Optional[str] = None  # delivery_id it is carrying


# ---------------------------------------------------------------------------
# Simulator
# ---------------------------------------------------------------------------

class DeliverySimulator:
    """
    Runs the AeroNet Lite delivery simulation step by step.

    Usage
    -----
        sim = DeliverySimulator(grid, drones, deliveries)
        sim.run(steps=20)
    """

    def __init__(self, grid, drones: list, deliveries: list):
        """
        Parameters
        ----------
        grid       : 2D list of Cell objects (from grid_model.py)
        drones     : list of Drone objects   (from fleet_selector.py or defined manually)
        deliveries : list of Delivery objects
        """
        self.grid = grid
        self.drones = {d.drone_id: d for d in drones}
        self.deliveries = {d.delivery_id: d for d in deliveries}
        self.event_log = []
        self.step = 0

        # Counters for final summary
        self.completed = 0
        self.delayed   = 0
        self.failed    = 0

    # -----------------------------------------------------------------------
    # Logging
    # -----------------------------------------------------------------------

    def log(self, message):
        """Record and print a timestamped event log entry."""
        entry = f"Step {self.step:>2}: {message}"
        self.event_log.append(entry)
        print(entry)

    # -----------------------------------------------------------------------
    # Delivery assignment
    # -----------------------------------------------------------------------

    def assign_deliveries(self):
        """
        Assign pending deliveries to idle drones.
        Uses simple nearest-drone assignment: pick the idle drone whose
        home hub has the smallest Manhattan distance to the pickup point.
        """
        from astar_planner import manhattan

        pending = [d for d in self.deliveries.values() if d.status == "pending"]
        idle_drones = [d for d in self.drones.values() if d.status == "idle"]

        for delivery in pending:
            if not idle_drones:
                break

            # Find the closest idle drone by Manhattan distance hub -> pickup
            best_drone = min(
                idle_drones,
                key=lambda drone: manhattan(drone.position, delivery.pickup)
            )

            # Plan the full route
            full_path, total_cost, segments, ok = plan_delivery_route(
                hub=best_drone.home_hub,
                pickup=delivery.pickup,
                dropoff=delivery.dropoff,
                grid=self.grid
            )

            if ok:
                best_drone.route = full_path[1:]  # exclude current position (already there)
                best_drone.route_cost = total_cost
                best_drone.status = "en_route"
                best_drone.current_delivery = delivery.delivery_id

                delivery.status = "assigned"
                delivery.assigned_drone = best_drone.drone_id

                idle_drones.remove(best_drone)

                self.log(
                    f"Delivery {delivery.delivery_id} assigned to Drone {best_drone.drone_id} "
                    f"(cost={total_cost}, steps={len(full_path)})"
                )
            else:
                # Report which segment failed
                failed_segs = [
                    seg for seg, data in segments.items()
                    if data["message"] != "success"
                ]
                delivery.status = "failed"
                self.failed += 1
                self.log(
                    f"Delivery {delivery.delivery_id} FAILED to plan — "
                    f"no safe path in segments: {failed_segs}"
                )

    # -----------------------------------------------------------------------
    # Drone movement
    # -----------------------------------------------------------------------

    def move_drones(self):
        """Advance each active drone one step along its planned route."""
        for drone in self.drones.values():
            if drone.status not in ("en_route", "returning"):
                continue

            if not drone.route:
                # Drone has reached the end of its route
                self._handle_route_complete(drone)
                continue

            # Move one cell
            next_cell = drone.route.pop(0)

            # Safety check: do not enter a no-fly cell
            # (should not happen if rerouting worked, but defensive check)
            if self.grid[next_cell[0]][next_cell[1]].no_fly:
                self.log(
                    f"Drone {drone.drone_id} blocked by unexpected no-fly cell at {next_cell}. "
                    f"Triggering emergency reroute."
                )
                drone.route.insert(0, next_cell)  # put it back
                self._reroute_drone(drone)
                return

            drone.position = next_cell

    def _handle_route_complete(self, drone):
        """Called when a drone finishes its entire route."""
        delivery = self.deliveries.get(drone.current_delivery)

        if delivery and delivery.status in ("assigned", "in_progress"):
            delivery.status = "completed"
            self.completed += 1
            self.log(
                f"Drone {drone.drone_id} completed delivery {drone.current_delivery} "
                f"and returned to hub {drone.home_hub}"
            )

        drone.status = "idle"
        drone.current_delivery = None
        drone.route = []
        drone.position = drone.home_hub

    # -----------------------------------------------------------------------
    # Disruption handling
    # -----------------------------------------------------------------------

    def activate_no_fly(self, row, col):
        """
        Activate a no-fly cell at (row, col) during simulation.
        Any drone whose remaining route passes through this cell is rerouted.

        Parameters
        ----------
        row, col : int - coordinates of the new no-fly cell
        """
        self.grid[row][col].no_fly = True
        self.log(f"No-fly cell activated at ({row}, {col})")

        for drone in self.drones.values():
            if drone.status not in ("en_route", "returning"):
                continue

            if (row, col) in drone.route:
                self.log(
                    f"Drone {drone.drone_id} route crosses newly blocked cell ({row}, {col}) — rerouting"
                )
                self._reroute_drone(drone)

    def _reroute_drone(self, drone):
        """
        Replan the drone's route from its current position to its next target
        using A* — handles the real-time disruption requirement from the spec.

        The drone's next target is the first cell in its remaining route that
        is NOT the newly blocked cell.
        """
        delivery = self.deliveries.get(drone.current_delivery)

        # Determine the goal: delivery dropoff if carrying, else home hub
        if delivery and delivery.status in ("assigned", "in_progress"):
            delivery.status = "in_progress"

            # Goal: delivery dropoff (or hub if already past dropoff)
            goal = delivery.dropoff if drone.status == "en_route" else drone.home_hub
        else:
            goal = drone.home_hub

        new_path, new_cost, msg = astar(drone.position, goal, self.grid)

        if msg == "success":
            drone.route = new_path[1:]  # exclude current position
            drone.route_cost = new_cost
            self.log(
                f"Drone {drone.drone_id} rerouted successfully using A* "
                f"(new cost={new_cost}, steps={len(new_path)})"
            )
        else:
            # No safe path exists after disruption
            drone.status = "grounded"
            if delivery:
                delivery.status = "delayed"
                self.delayed += 1
                self.log(
                    f"Drone {drone.drone_id} CANNOT reach destination safely — "
                    f"delivery {drone.current_delivery} marked as DELAYED. Reason: {msg}"
                )
            else:
                self.log(
                    f"Drone {drone.drone_id} CANNOT return to hub safely. Grounded. Reason: {msg}"
                )

    # -----------------------------------------------------------------------
    # Main simulation runner
    # -----------------------------------------------------------------------

    def run(self, total_steps=20, no_fly_events=None, anomaly_step=None):
        """
        Run the simulation for the given number of steps.

        Parameters
        ----------
        total_steps    : int  - total simulation steps (default 20 per spec)
        no_fly_events  : dict - {step_number: (row, col)} of no-fly activations
                               e.g. {11: (4, 7)}
        anomaly_step   : int  - step at which an anomaly is reported
                               (anomaly detection itself is Member 4's ML pipeline)
        """
        if no_fly_events is None:
            no_fly_events = {}

        print("=" * 60)
        print("  AeroNet Lite — Delivery Simulation")
        print("=" * 60)

        for step in range(1, total_steps + 1):
            self.step = step

            # --- Steps 1-3: Initialisation phase (caller handles grid + fleet) ---
            if step == 1:
                self.log("Simulation started. Grid and fleet ready.")

            # --- Steps 4-6: Generate and assign deliveries ---
            elif step == 4:
                self.assign_deliveries()

            # --- Steps 7-10: Move drones ---
            elif 7 <= step <= 10:
                self.move_drones()

            # --- Steps 11-14: Disruption phase ---
            elif step in no_fly_events:
                row, col = no_fly_events[step]
                self.activate_no_fly(row, col)
                self.move_drones()

            elif 11 <= step <= 14:
                self.move_drones()

            # --- Steps 15-17: Continue moving; ML pipeline runs in parallel ---
            elif 15 <= step <= 17:
                self.move_drones()
                if step == 15:
                    self.log("Demand forecast running (see ml_pipeline.py)")

            # --- Step 18: Anomaly detection hook ---
            elif step == 18:
                self.move_drones()
                if anomaly_step == 18:
                    self.log(
                        "Anomaly detected by ML pipeline — see ml_pipeline.py for details"
                    )

            # --- Step 19: Post-anomaly movement ---
            elif step == 19:
                self.move_drones()

            # --- Step 20: Final summary ---
            elif step == 20:
                self.move_drones()
                self._print_summary()

            else:
                # Default: keep moving drones
                self.move_drones()

        return self.event_log

    # -----------------------------------------------------------------------
    # Summary
    # -----------------------------------------------------------------------

    def _print_summary(self):
        """Print the final simulation summary (Step 20 output per spec)."""

        # Count any drones still active at end as delayed
        for drone in self.drones.values():
            if drone.status in ("en_route", "returning") and drone.current_delivery:
                delivery = self.deliveries.get(drone.current_delivery)
                if delivery and delivery.status not in ("completed", "delayed", "failed"):
                    delivery.status = "delayed"
                    self.delayed += 1

        total = len(self.deliveries)
        still_pending = sum(
            1 for d in self.deliveries.values() if d.status == "pending"
        )
        self.failed += still_pending  # anything never assigned counts as failed

        print("-" * 60)
        self.log(
            f"Simulation complete. "
            f"{self.completed} completed, "
            f"{self.delayed} delayed, "
            f"{self.failed} failed."
        )
        print("=" * 60)
        print("\nFull delivery status:")
        for d in self.deliveries.values():
            drone_info = f"(Drone {d.assigned_drone})" if d.assigned_drone else "(unassigned)"
            print(f"  {d.delivery_id} {drone_info}: {d.status.upper()}")

    def print_log(self):
        """Print the complete event log."""
        print("\n--- Full Event Log ---")
        for entry in self.event_log:
            print(entry)


# ---------------------------------------------------------------------------
# Standalone demo
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    # ---- Build grid ----
    try:
        from grid_model import build_sample_grid
        grid = build_sample_grid()
        print("Loaded grid from grid_model.py\n")
    except ImportError:
        from dataclasses import dataclass as dc

        @dc
        class Cell:
            row: int
            col: int
            zone: str = "Open"
            no_fly: bool = False
            is_commercial_corridor: bool = False
            is_hub: bool = False

        grid = [[Cell(row=r, col=c) for c in range(10)] for r in range(10)]
        # Mark hubs
        for r, c in [(2, 5), (7, 2)]:
            grid[r][c].is_hub = True
        # Commercial corridors
        for r, c in [(3, 4), (3, 5), (4, 5), (5, 5)]:
            grid[r][c].is_commercial_corridor = True
        print("grid_model.py not found — using minimal inline grid\n")

    # ---- Define drones ----
    # Normally these come from fleet_selector.py (Member 2)
    drones = [
        Drone(drone_id="D1", drone_type="light", position=(2, 5), home_hub=(2, 5)),
        Drone(drone_id="D2", drone_type="light", position=(2, 5), home_hub=(2, 5)),
        Drone(drone_id="D3", drone_type="heavy", position=(7, 2), home_hub=(7, 2)),
    ]

    # ---- Define deliveries ----
    deliveries = [
        Delivery("DEL-1", hub=(2, 5), pickup=(0, 0), dropoff=(9, 9)),
        Delivery("DEL-2", hub=(2, 5), pickup=(1, 3), dropoff=(8, 6)),
        Delivery("DEL-3", hub=(7, 2), pickup=(6, 0), dropoff=(3, 8)),
        Delivery("DEL-4", hub=(7, 2), pickup=(9, 1), dropoff=(0, 8)),
    ]

    # ---- No-fly events: cell (4,7) becomes no-fly at step 11 ----
    no_fly_events = {11: (4, 7)}

    # ---- Run ----
    sim = DeliverySimulator(grid, drones, deliveries)
    sim.run(total_steps=20, no_fly_events=no_fly_events, anomaly_step=18)