# -*- coding: utf-8 -*-
"""fleet_selector.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-4EYlOF9f8C3qQucwJgEPBrCCioebzJh
"""

"""
AeroNet Lite - Module 2: Fleet Selector

Selects the best combination of light and heavy drones
under a fixed budget using both Brute Force and a
Genetic Algorithm (GA).

Drone Types:
  - Light Drone : cost=1000, payload=2kg, range=12 cells
  - Heavy Drone : cost=1800, payload=5kg, range=20 cells

Fitness Formula:
  score = (0.75 x coverage_%) - (0.25 x budget_used_%)
"""

import random

#  DRONE SPECIFICATIONS

DRONE_TYPES = {
    "light": {
        "cost":    1000,
        "payload": 2,      # kg
        "range":   12,     # cells
    },
    "heavy": {
        "cost":    1800,
        "payload": 5,      # kg
        "range":   20,     # cells
    },
}


#  FITNESS FUNCTION  (shared by both methods)
def calculate_fitness(light_count, heavy_count, budget):
    """
    Returns a fitness score for a given fleet combination.

    Coverage is estimated as:
      - Each light drone covers  12 cells  (its range)
      - Each heavy drone covers  20 cells  (its range)
      - Max possible coverage   = 100 cells (10x10 grid)

    The formula rewards high coverage and punishes overspending.
    score = 0.75 * coverage_pct  -  0.25 * budget_used_pct

    Returns -infinity if the fleet exceeds the budget,
    so invalid solutions are automatically rejected.
    """
    total_cost = (light_count * DRONE_TYPES["light"]["cost"] +
                  heavy_count * DRONE_TYPES["heavy"]["cost"])

    # Reject any fleet that goes over budget
    if total_cost > budget:
        return float("-inf")

    # Estimate how many cells the fleet can cover
    # (capped at 100 because the grid is 10x10)
    GRID_SIZE = 100
    coverage = min(
        light_count * DRONE_TYPES["light"]["range"] +
        heavy_count * DRONE_TYPES["heavy"]["range"],
        GRID_SIZE
    )

    coverage_pct    = (coverage    / GRID_SIZE) * 100   # 0 – 100
    budget_used_pct = (total_cost  / budget)    * 100   # 0 – 100

    score = (0.75 * coverage_pct) - (0.25 * budget_used_pct)
    return round(score, 4)


# ─────────────────────────────────────────────
#  OPTION A: BRUTE FORCE
# ─────────────────────────────────────────────
def brute_force_select(budget):
    """
    Tries every possible combination of light and heavy drones
    that fits within the budget.

    Max drones of each type we ever need to check:
      max_light = budget // 1000
      max_heavy = budget // 1800
    """
    best_score  = float("-inf")
    best_fleet  = (0, 0)

    max_light = budget // DRONE_TYPES["light"]["cost"]
    max_heavy = budget // DRONE_TYPES["heavy"]["cost"]

    for light in range(max_light + 1):
        for heavy in range(max_heavy + 1):
            score = calculate_fitness(light, heavy, budget)
            if score > best_score:
                best_score = score
                best_fleet = (light, heavy)

    return best_fleet, best_score


# ─────────────────────────────────────────────
#  OPTION B: GENETIC ALGORITHM
# ─────────────────────────────────────────────
def genetic_algorithm_select(
    budget,
    population_size = 20,
    generations     = 50,
    mutation_rate   = 0.1,
):
    """
    Uses a Genetic Algorithm to evolve a good fleet.

    Each 'chromosome' (individual) is a list:
        [light_count, heavy_count]

    Steps per generation:
      1. Evaluate fitness of every individual
      2. Select the top 50% as parents (elitism)
      3. Create children via crossover
      4. Apply random mutation
      5. Repeat for N generations
    """

    max_light = budget // DRONE_TYPES["light"]["cost"]
    max_heavy = budget // DRONE_TYPES["heavy"]["cost"]

    # ── Step 1: Create initial random population ──────────────
    def random_individual():
        return [
            random.randint(0, max_light),
            random.randint(0, max_heavy),
        ]

    population = [random_individual() for _ in range(population_size)]

    # ── Step 2: Evolve over generations ───────────────────────
    for gen in range(generations):

        # Score every individual
        scored = [
            (ind, calculate_fitness(ind[0], ind[1], budget))
            for ind in population
        ]

        # Sort best → worst  (put -inf last)
        scored.sort(key=lambda x: x[1] if x[1] != float("-inf") else -9999,
                    reverse=True)

        # Keep top 50% as survivors (elitism)
        survivors = [ind for ind, _ in scored[: population_size // 2]]

        # Fill the rest of the population with children
        children = []
        while len(children) < population_size - len(survivors):

            # Pick two random parents from survivors
            parent_a = random.choice(survivors)
            parent_b = random.choice(survivors)

            # Crossover: child inherits light from A, heavy from B
            child = [parent_a[0], parent_b[1]]

            # Mutation: randomly tweak one gene
            if random.random() < mutation_rate:
                gene = random.randint(0, 1)   # 0 = light, 1 = heavy
                if gene == 0:
                    child[0] = random.randint(0, max_light)
                else:
                    child[1] = random.randint(0, max_heavy)

            children.append(child)

        population = survivors + children

    # ── Step 3: Return the best individual found ───────────────
    best_individual = max(
        population,
        key=lambda ind: (
            calculate_fitness(ind[0], ind[1], budget)
            if calculate_fitness(ind[0], ind[1], budget) != float("-inf")
            else -9999
        ),
    )
    best_light, best_heavy = best_individual
    best_score = calculate_fitness(best_light, best_heavy, budget)

    return (best_light, best_heavy), best_score


# ─────────────────────────────────────────────
#  MAIN RUNNER
# ─────────────────────────────────────────────
def select_fleet(budget, method="ga"):
    """
    Public function that Member 4 calls from main.py.

    Parameters:
        budget : int   – total money available (e.g. 10000)
        method : str   – "brute" or "ga"

    Returns:
        fleet  : dict  – {"light": N, "heavy": M}
        score  : float – fitness score of selected fleet
    """

    print("\n" + "=" * 50)
    print("  MODULE 2 – FLEET SELECTOR")
    print("=" * 50)
    print(f"  Budget  : ₹{budget}")
    print(f"  Method  : {'Genetic Algorithm' if method == 'ga' else 'Brute Force'}")
    print("-" * 50)

    if method == "brute":
        (light, heavy), score = brute_force_select(budget)
    else:
        (light, heavy), score = genetic_algorithm_select(budget)

    total_cost    = light * 1000 + heavy * 1800
    budget_left   = budget - total_cost
    total_drones  = light + heavy

    print(f"\n  Best fleet found:")
    print(f"    Light drones  : {light}  × ₹1000 = ₹{light * 1000}")
    print(f"    Heavy drones  : {heavy}  × ₹1800 = ₹{heavy * 1800}")
    print(f"    Total cost    : ₹{total_cost}  (₹{budget_left} remaining)")
    print(f"    Total drones  : {total_drones}")
    print(f"    Fitness score : {score}")

    # Summarise what the fleet can do
    GRID_SIZE   = 100
    coverage    = min(light * 12 + heavy * 20, GRID_SIZE)
    print(f"\n  Fleet capability:")
    print(f"    Max grid coverage : {coverage} / {GRID_SIZE} cells")
    print(f"    Heavy payload     : up to {heavy * 5} kg per batch")
    print(f"    Light payload     : up to {light * 2} kg per batch")
    print("=" * 50 + "\n")

    fleet = {"light": light, "heavy": heavy}
    return fleet, score


# ─────────────────────────────────────────────
#  STANDALONE TEST
# ─────────────────────────────────────────────
if __name__ == "__main__":

    BUDGET = 10_000   # ₹10,000

    # --- Test Brute Force ---
    fleet_bf, score_bf = select_fleet(BUDGET, method="brute")

    # --- Test Genetic Algorithm ---
    fleet_ga, score_ga = select_fleet(BUDGET, method="ga")

    # --- Compare both ---
    print("COMPARISON")
    print(f"  Brute Force  →  {fleet_bf}  score={score_bf}")
    print(f"  Genetic Alg  →  {fleet_ga}  score={score_ga}")

    # --- Show fitness for a few manual combinations ---
    print("\nMANUAL FITNESS CHECK  (budget = ₹10,000)")
    combos = [(5, 0), (0, 5), (3, 2), (4, 2), (2, 3), (6, 1)]
    for l, h in combos:
        s = calculate_fitness(l, h, BUDGET)
        cost = l * 1000 + h * 1800
        tag  = "✔" if cost <= BUDGET else "✘ over budget"
        print(f"  Light={l}, Heavy={h} → cost=₹{cost}  score={s}  {tag}")